FROM ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -y git curl xz-utils tar gpg build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev \
    libncursesw5-dev tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    libffi8 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5 pkg-config

RUN groupadd -g 1001 asdf
RUN adduser -u 1001 --gid 1001 --shell /bin/bash --home /asdf --disabled-password asdf
ENV PATH="${PATH}:/asdf/.asdf/shims:/asdf/.asdf/bin"

USER asdf
RUN git clone --depth 1 https://github.com/asdf-vm/asdf.git $HOME/.asdf && \
    echo '. $HOME/.asdf/asdf.sh' >> $HOME/.bashrc && \
    echo '. $HOME/.asdf/asdf.sh' >> $HOME/.profile

RUN . ~/.bashrc

# YOLO
RUN curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

ENV PATH="${PATH}:/asdf/.ghcup/bin"

RUN asdf plugin add nodejs && \
    asdf plugin add golang && \
    asdf plugin add shellcheck && \
    asdf plugin add yarn && \
    asdf plugin add python && \
    asdf plugin add rust

COPY .tool-versions .

RUN asdf install && \
    # Pre-fetch Haskell dependencies as they take the longest time by far
    # TODO(anton): run the proto-generate.sh script during the build time to 
    # pre-fecth all dependencies. I attempted to do so but ran into issues 
    # with Yarn
    cabal install proto-lens-protoc-0.8.0.1 ghc-source-gen-0.4.5.0 

WORKDIR /src

CMD ["./dev/docker-entrypoint.sh"]


