name: Check TypeScript

on:
  pull_request:
    paths:
      - '**.ts'
      - '**/package.json'
      - '**/tsconfig.json'
      - '**/yarn.lock'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Avoid using separate GitHub Actions for installing toolchains for
        # Go, Rust etc. Maintaining all toolchain versions with asdf using
        # a single .tool-versions file is easier.
      - name: Install asdf
        run: |
          set -e
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 --depth=1

      - name: Check TypeScript
        run: |
          set -e
          source ~/.asdf/asdf.sh
          asdf plugin-add yarn
          asdf install yarn
          asdf plugin-add nodejs
          asdf install nodejs

          cd bindings/typescript
          yarn install --frozen-lockfile
          ./node_modules/typescript/bin/tsc -b .
