name: 'Check synced and well-formed generated output'

on:
  pull_request:
    paths:
      - '**/scip.*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Avoid using separate GitHub Actions for installing toolchains for
        # Go, Rust etc. Maintaining all toolchain versions with asdf using
        # a single .tool-versions file is easier.
      - name: Install asdf
        run: |
          set -e
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 --depth=1

      - name: Install Go for protobuf conversion
        run: |
          source ~/.asdf/asdf.sh
          asdf plugin-add golang
          asdf install golang

      - name: Check that generated files are up-to-date
        run: |
          set -e
          ./dev/proto-generate.sh
          git diff --quiet

      - name: Check Go
      - run: |
          set -e
          go test ./...

      - name: Check Rust
        run: |
          set -e
          source ~/.asdf/asdf.sh
          asdf plugin-add rust
          asdf install rust
          cd bindings/rust
          cargo check

      - name: Check TypeScript
        run: |
          set -e
          source ~/.asdf/asdf.sh
          asdf plugin-add yarn
          asdf install yarn
          asdf plugin-add nodejs
          asdf install nodejs
          cd bindings/typescript
          yarn install --frozen-lockfile
          ./node_modules/typescript/bin/tsc -b .
