name: Check schema in sync

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'bindings/**'
      - 'scip.proto'
      - 'buf**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Avoid using separate GitHub Actions for installing toolchains for
        # Go, Rust etc. Maintaining all toolchain versions with asdf using
        # a single .tool-versions file is easier.
      - name: Install asdf
        run: |
          set -e
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 --depth=1

      - name: Install Go for protobuf conversion
        run: |
          source ~/.asdf/asdf.sh
          asdf plugin-add golang
          asdf install golang

      - name: Check that generated files are up-to-date
        run: |
          set -e
          ./dev/proto-generate.sh
          git diff --exit-code
