name: CI

on:
  pull_request:
    paths:
      - '**.go'

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: '1.18' }
      - name: Test Go
        run: go test ./...
