name: "Crate Release (Dry Run)"

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  release-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/asdf
        with:
          rust: true
      - run: cargo publish --dry-run
        working-directory: bindings/rust
