name: Haskell
on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**.hs'
      - '**.cabal'

jobs:
  haskell-typecheck:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10'
          cabal-version: 'latest'
      - name: Build source
        run: cabal build --ghc-options='-j2 +RTS -A32m'
        working-directory: bindings/haskell
