name: Nix

on:
  pull_request:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.checks.outputs.result }}
      packages: ${{ steps.packages.outputs.result }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - id: checks
        run: >
          echo "result=$(
            nix eval .#checks.x86_64-linux --apply builtins.attrNames --json
          )" >> "$GITHUB_OUTPUT"
      - id: packages
        run: >
          echo "result=$(
            nix eval .#packages.x86_64-linux
              --apply builtins.attrNames
              --apply 'builtins.filter (n: n != "default")'
              --json
          )" >> "$GITHUB_OUTPUT"

  checks:
    needs: list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ${{ fromJSON(needs.list.outputs.checks) }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix build .#checks.x86_64-linux.${{ matrix.check }}

  packages:
    needs: list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.list.outputs.packages) }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix run .#${{ matrix.package }}
      - run: git diff --exit-code

  nix-checks-pass:
    if: always()
    needs: [checks, packages]
    runs-on: ubuntu-latest
    steps:
      - if: >-
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        run: exit 1
