# Copied from https://github.com/sourcegraph/scip-typescript/blob/main/.github/workflows/project-board.yml
name: Project Board
on:
  issues:
    types:
      - opened
jobs:
  # Uses issues beta API - see https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow
  code-intel-board:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: MDExOlByb2plY3ROZXh0NDI1MA== # https://github.com/orgs/sourcegraph/projects/211
      GITHUB_TOKEN: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
    steps:
      - name: Add to board
        env:
          NODE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($project:ID!, $node_id:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $node_id}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f node_id=$NODE_ID
